# Generated by Django 5.2.1 on 2025-06-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the announcement', max_length=200, verbose_name='Title')),
                ('description', models.TextField(help_text='Enter the description of the announcement', verbose_name='Description')),
                ('start_date', models.DateTimeField(help_text='Enter the start date of the announcement', verbose_name='Start Date')),
                ('end_date', models.DateTimeField(help_text='Enter the end date of the announcement', verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the announcement was created', verbose_name='Created At')),
                ('slide', models.FileField(blank=True, help_text='Upload a slide image for the announcement', null=True, upload_to='announcements/', verbose_name='Slide')),
                ('chapel', models.BooleanField(default=False, help_text='Indicates if the announcement is for chapel', verbose_name='Chapel')),
                ('praise', models.BooleanField(default=False, help_text='Indicates if the announcement is for praise', verbose_name='Praise')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-start_date'],
            },
        ),
    ]
