# Generated by Django 5.2.1 on 2025-06-03 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcement',
            new_name='Submission',
        ),
    ]
