# Generated by Django 5.2.1 on 2025-06-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_rename_announcement_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='name',
            field=models.CharField(default='Anonymous', help_text='Enter your name', max_length=100, verbose_name='Name'),
        ),
    ]
