# Generated by Django 5.2.1 on 2025-07-01 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_remove_submission_name_submission_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='slide',
        ),
        migrations.CreateModel(
            name='SubmissionSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='announcements/')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='submission.submission')),
            ],
        ),
    ]
