# Generated by Django 5.2.1 on 2025-08-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_remove_submission_slide_submissionslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.TextField(blank=True, help_text='Enter the description of the announcement', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter the email address to contact for any questions', max_length=254, null=True, verbose_name='Contact Email'),
        ),
    ]
