# Generated by Django 5.2.1 on 2025-08-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_alter_submission_description_alter_submission_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the contact person', max_length=100, verbose_name='Name')),
                ('email', models.EmailField(help_text='Enter the email address of the contact person', max_length=254, verbose_name='Email')),
                ('is_chapel', models.BooleanField(default=False, help_text='Indicates if this contact is for chapel announcements', verbose_name='Chapel Contact')),
                ('is_praise', models.BooleanField(default=False, help_text='Indicates if this contact is for praise announcements', verbose_name='Praise Contact')),
            ],
        ),
    ]
