# Generated by Django 5.2.1 on 2025-08-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='chapel',
            new_name='is_chapel',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='praise',
        ),
        migrations.AddField(
            model_name='submission',
            name='is_praise',
            field=models.BooleanField(default=True, help_text='Indicates if the announcement is for praise', verbose_name='Praise'),
        ),
    ]
